appteams/urls.py
from django.urls import path
from . import views

app_name="appteams"
urlpatterns = [
    path('', views.ver_equipos),
    path('registrar-cedula/', views.cedulas_view),
    path('registrar-arbitro/', views.arbitros_view),
    path('registrar-equipo/', views.equipos_view),
    path('registrar-League/', views.League_view),
    path('registrar-estadio/', views.estadios_view),
    path('registrar-Play/', views.Play_view),
    path('registrar-coach/', views.coachs_view),
    path('registrar-jugador/', views.jugadores_view),
    path('equipos/',views.ver_equipos),
    path('cedulas/',views.ver_cedulas),
    path('League/', views.ver_ligas),
    path('plays/', views.ver_juegos),
    path('estadios/', views.ver_estadios),
    path('arbitros/', views.ver_arbitros),
    path('jugadores/',views.ver_jugadores),
    path('coachs/',views.ver_coachs),
    path('eliminar-jugador/<int:id>', views.eliminarJugador, name= 'eliminar-jugador'),
    path('eliminar-coach/<int:id>', views.eliminarCoach, name= 'eliminar-coach'),
    path('eliminar-equipo/<int:id>', views.eliminarEquipos, name= 'eliminar-equipo'),
    path('eliminar-arbitro/<int:id>', views.eliminarArbitros, name= 'eliminar-arbitro'),
    path('eliminar-liga/<int:id>', views.eliminarLigas, name= 'eliminar-liga'),
    path('eliminar-cedula/<int:id>', views.eliminarCedulas, name= 'eliminar-cedula'),
    path('eliminar-juego/<int:id>', views.eliminarJuegos, name= 'eliminar-juego'),
    path('eliminar-estadio/<int:id>', views.eliminarEstadios, name= 'eliminar-estadio'),
    path('editar-jugador/<int:id>', views.editarJugador,name='editar-jugador'),
    path('editar-cedula/<int:id>', views.editarCedula,name='editar-cedula'),
    path('editar-equipo/<int:id>', views.editarEquipo,name='editar-equipo'),
    path('editar-arbitro/<int:id>', views.editarArbitro,name='editar-arbitro'),
    path('editar-coach/<int:id>', views.editarCoach,name='editar-coach'),
    path('editar-estadio/<int:id>', views.editarEstadio,name='editar-estadio'),
    path('editar-liga/<int:id>', views.editarLiga,name='editar-liga'),
    path('editar-juego/<int:id>', views.editarJuego,name='editar-juego'),
]

teams/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
##Estas importaciones son para poder que django pinte las imagenes 
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('appteams.urls'))
    
]

if settings.DEBUG: #new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

appteams/forms.py
from django import forms
from .models import cedulas,arbitros,equipos,League,Play,jugadores,estadios,coachs
from django.contrib.admin import widgets

class cedulas(forms.ModelForm):
    fecha_inicio=forms.DateTimeField(
        label='Fecha Inicio',
        widget=forms.DateTimeInput(attrs={'class': 'datetimepicker', 'type': 'datetime-local'}),)
    fecha_fin=forms.DateTimeField(
        label='Fecha Fin',
        widget=forms.DateTimeInput(attrs={'class': 'datetimepicker', 'type': 'datetime-local'}),)
    class Meta:
        model = cedulas
        fields = ["name","play_id","play_desc","resultado","fecha_inicio","fecha_fin"]

class arbitros(forms.ModelForm):
    class Meta:
        model = arbitros
        fields = ["liga_id","name","photo"]

class equipos(forms.ModelForm):
    class Meta:
        model = equipos
        fields = ["liga_id","name","coach_id", "photo"]
        
class League (forms.ModelForm):
    class Meta:
        model = League
        fields = ("name","foto")

class Play(forms.ModelForm):
    fecha = forms.DateTimeField(
        label='Fecha',
        widget=forms.DateTimeInput(attrs={'class': 'datetimepicker', 'type': 'datetime-local'}),)
    class Meta:
        model = Play
        fields = ["folio","fecha","liga","team1","team2","estadio","arbitro_1","posicion_arbitro_1", "arbitro_2","posicion_arbitro_2", "arbitro_3","posicion_arbitro_3", "arbitro_4","posicion_arbitro_4"]
        
    

class jugadores(forms.ModelForm):
    class Meta:
        model = jugadores
        fields = ["team","name","photo","numero","posicion"]

class estadios(forms.ModelForm):
    class Meta:
        model = estadios
        fields = ["liga_id","name","photo"]

class coachs(forms.ModelForm):
    class Meta:
        model = coachs
        fields = ["name","photo"]    

appteams/views.py
from django.shortcuts import render, redirect
from django.core.exceptions import ObjectDoesNotExist
from .forms import cedulas,arbitros,equipos,League,Play,jugadores,estadios,coachs
from . import models 

#_________FUNCIONES DE LOS FORMULARIOS____________________
def cedulas_view(request):
    if request.method == 'POST':
        form = cedulas(request.POST, request.FILES)
        
        if form.is_valid():
            form.save()
            # Realiza alguna acción después de guardar el formulario
    else:
        form = cedulas()

    context = {
        'form': form
    }
    return render(request, 'formulario.html', context)

def arbitros_view(request):
    if request.method == 'POST':
        form = arbitros(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            # Realiza alguna acción después de guardar el formulario
    else:
        form = arbitros()

    context = {
        'form': form
    }
    return render(request, 'formulario.html', context)

def equipos_view(request):
    if request.method == 'POST':
        form = equipos(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            # Realiza alguna acción después de guardar el formulario
    else:
        form = equipos()

    context = {
        'form': form
    }
    return render(request, 'formulario.html', context)

def League_view(request):
    if request.method == 'POST':
        form = League(request.POST, request.FILES)
        print("Recibiendo el formulario 2")
        print(form.fields)
        if form.is_valid():
            print("Recibiendo el formulario")
            print(form.fields)
            form.save()
            # Realiza alguna acción después de guardar el formulario
    else:
        form = League()
        print("Entro aqui   ")

    context = {
        'form': form
    }
    return render(request, 'formulario.html', context)

def Play_view(request):
    if request.method == 'POST':
        form = Play(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            # Realiza alguna acción después de guardar el formulario
    else:
        form = Play()

    context = {
        'form': form
    }
    return render(request, 'formulario.html', context)

def jugadores_view(request):
    if request.method == 'POST':
        form = jugadores(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            # Realiza alguna acción después de guardar el formulario
    else:
        form = jugadores()

    context = {
        'form': form
    }
    return render(request, 'formulario.html', context)

def estadios_view(request):
    if request.method == 'POST':
        form = estadios(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            # Realiza alguna acción después de guardar el formulario
    else:
        form = estadios()

    context = {
        'form': form
    }
    return render(request, 'formulario.html', context)

def coachs_view(request):
    if request.method == 'POST':
        form = coachs(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            # Realiza alguna acción después de guardar el formulario
    else:
        form = coachs()

    context = {
        'form': form
    }
    return render(request, 'formulario.html', context)

##________________FUNCIONES PARA MOSTRAR LA INFO__________________

def ver_equipos(request):
    ver_equipos = models.equipos.objects.all()  
    return render(request,'equipos.html',{
        'equipos' : ver_equipos
    })
    
def ver_cedulas(request):
    ver_cedulas = models.cedulas.objects.all()
    return render(request,'cedulas.html',{
        'cedulas' : ver_cedulas,
    })
def ver_jugadores(request):
    ver_jugadores = models.jugadores.objects.all()  
    return render(request,'jugadores.html',{
        'jugadores' : ver_jugadores
    })

def ver_coachs(request):
    ver_coachs = models.coachs.objects.all()  
    return render(request,'coachs.html',{
        'coachs' : ver_coachs
    })

def ver_ligas(request):
    ver_ligas = models.League.objects.all()
    return render(request, 'ligas.html', {
        'ligas': ver_ligas
    })

def ver_juegos(request):
    ver_juegos = models.Play.objects.all()
    return render(request, 'plays.html', {
        'juegos': ver_juegos
    })

def ver_estadios(request):
    ver_estadios = models.estadios.objects.all()
    return render(request, 'estadios.html', {
        'estadios': ver_estadios
    })

def ver_arbitros(request):
    ver_arbitros = models.arbitros.objects.all()
    return render(request, 'arbitros.html', {
        'arbitros': ver_arbitros
    })
#Funciones de eliminar

def eliminarJugador(request,id):
    jugador = models.jugadores.objects.get(id = id)
    jugador.delete()
    return redirect('http://127.0.0.1:8000/jugadores/')

def eliminarCoach(request,id):
    coach = models.coachs.objects.get(id = id)
    coach.delete()
    return redirect('http://127.0.0.1:8000/coachs/')

def eliminarEquipos(request,id):
    equipo = models.equipos.objects.get(id = id)
    equipo.delete()
    return redirect('http://127.0.0.1:8000/equipos/')

def eliminarArbitros(request,id):
    arbitro = models.arbitros.objects.get(id = id)
    arbitro.delete()
    return redirect('http://127.0.0.1:8000/arbitros/')

def eliminarLigas(request,id):
    liga = models.League.objects.get(id = id)
    liga.delete()
    return redirect('http://127.0.0.1:8000/League/')

def eliminarCedulas(request,id):
    cedula = models.cedulas.objects.get(id = id)
    cedula.delete()
    return redirect('http://127.0.0.1:8000/cedulas/')

def eliminarJuegos(request,id):
    juego = models.Play.objects.get(id = id)
    juego.delete()
    return redirect('http://127.0.0.1:8000/plays/')

def eliminarEstadios(request,id):
    estadio = models.estadios.objects.get(id = id)
    estadio.delete()
    return redirect('http://127.0.0.1:8000/estadios/')

#Funciones de editar

def editarJugador(request,id):
    form = None 
    error = None
    try:
        jugador = models.jugadores.objects.get(id = id)
        if request.method == 'GET':
            form = jugadores(instance = jugador)
        else:
            form = jugadores(request.POST, request.FILES,instance = jugador)
            if form.is_valid():
                form.save()
            return redirect('http://127.0.0.1:8000/jugadores/')
    except ObjectDoesNotExist as e:
        error = e
    
    return render(request,'formulario.html',{'form':form,'error':error})

def editarCedula(request,id):
    form = None 
    error = None
    try:
        cedula = models.cedulas.objects.get(id = id)
        if request.method == 'GET':
            form = cedulas(instance = cedula)
        else:
            form = cedulas(request.POST, request.FILES,instance = cedula)
            if form.is_valid():
                form.save()
            return redirect('http://127.0.0.1:8000/cedulas/')
    except ObjectDoesNotExist as e:
        error = e
    
    return render(request,'formulario.html',{'form':form,'error':error})

def editarEquipo(request,id):
    form = None 
    error = None
    try:
        equipo = models.equipos.objects.get(id = id)
        if request.method == 'GET':
            form = equipos(instance = equipo)
        else:
            form = equipos(request.POST, request.FILES,instance = equipo)
            if form.is_valid():
                form.save()
            return redirect('http://127.0.0.1:8000/equipos/')
    except ObjectDoesNotExist as e:
        error = e
    
    return render(request,'formulario.html',{'form':form,'error':error})

def editarArbitro(request,id):
    form = None 
    error = None
    try:
        arbitro = models.arbitros.objects.get(id = id)
        if request.method == 'GET':
            form = arbitros(instance = arbitro)
        else:
            form = arbitros(request.POST, request.FILES,instance = arbitro)
            if form.is_valid():
                form.save()
            return redirect('http://127.0.0.1:8000/equipos/')
    except ObjectDoesNotExist as e:
        error = e
    
    return render(request,'formulario.html',{'form':form,'error':error})

def editarCoach(request,id):
    form = None 
    error = None
    try:
        coach = models.coachs.objects.get(id = id)
        if request.method == 'GET':
            form = coachs(instance = coach)
        else:
            form = coachs(request.POST, request.FILES,instance = coach)
            if form.is_valid():
                form.save()
            return redirect('http://127.0.0.1:8000/equipos/')
    except ObjectDoesNotExist as e:
        error = e
    
    return render(request,'formulario.html',{'form':form,'error':error})

def editarEstadio(request,id):
    form = None 
    error = None
    try:
        estadio = models.estadios.objects.get(id = id)
        if request.method == 'GET':
            form = estadios(instance = estadio)
        else:
            form = estadios(request.POST, request.FILES,instance = estadio)
            if form.is_valid():
                form.save()
            return redirect('http://127.0.0.1:8000/equipos/')
    except ObjectDoesNotExist as e:
        error = e
    
    return render(request,'formulario.html',{'form':form,'error':error})

def editarLiga(request,id):
    form = None 
    error = None
    try:
        liga = models.League.objects.get(id = id)
        if request.method == 'GET':
            form = League(instance = liga)
        else:
            form = League(request.POST, request.FILES,instance = liga)
            if form.is_valid():
                form.save()
            return redirect('http://127.0.0.1:8000/equipos/')
    except ObjectDoesNotExist as e:
        error = e
    
    return render(request,'formulario.html',{'form':form,'error':error})
    
def editarJuego(request,id):
    form = None 
    error = None
    try:

appteams/templates/arbitros.html
{% extends 'layouts/barra.html' %}
{%block blockname%}
    <h1 class="titulo">Lista de Árbitros</h1>
    <div class="botones">
        <a href='/registrar-arbitro' class="agregar">Agregar</a>
    </div>
    <div class="contenedor-tabla">
        <table class="tabla">
            <tr >
                <td class="encabezado">Liga</td>
                <td class="encabezado">Nombre</td>
                <td class="encabezado">Foto</td>
                <td class="encabezado" colspan="2"></td>

            </tr>

            {%for arbitro in arbitros%}
            <tr>
                <td>{{arbitro.liga_id.name}}</td>
                <td>{{arbitro.name}}</td>
                <td><img src="{{ arbitro.photo.url }}" alt="Foto del arbitro" width="150"></td>
                <td><a href='/editar-arbitro/{{arbitro.id}}' class="editar">Editar</a></td>
                <td><a href="{% url 'appteams:eliminar-arbitro' arbitro.id %}" class="eliminar">Eliminar</a></td>
            {% endfor %}
        </table>
    </div>

{%endblock%}

appteams/templates/cedulas.html
{% extends 'layouts/barra.html' %}
{% load static %}
{%block blockname%}
    <h1 class="titulo">Lista de las cedulas</h1>
    <div class="botones">
        <a href='/registrar-cedula' class="agregar">Agregar</a>
    </div>
    <div class="contenedor-tabla">
        <table class="tabla">
            <tr >
                <td class="encabezado">Folio</td>
                <td class="encabezado">Juego</td>
                <td class="encabezado">Titulo</td>
                <td class="encabezado">Resultado</td>
                <td class="encabezado">Fecha de inicio</td>
                <td class="encabezado">Fecha de finalización</td>
                <td class="encabezado" colspan="2"></td>
            </tr>

            {%for cedula in cedulas%}
            <tr>
                <td>{{cedula.name}}</td>
                <td>{{cedula.play_id}}</td>
                <td>{{cedula.play_desc}}</td>
                <td>{{cedula.resultado}}</td>
                <td>{{cedula.fecha_inicio}}</td>
                <td>{{cedula.fecha_fin}}</td>
                <td><a href='/editar-cedula/{{cedula.id}}' class="editar">Editar</a></td>
                <td><a href="{% url 'appteams:eliminar-cedula' cedula.id %}" class="eliminar">Eliminar</a></td>
                
            </tr>
            {% endfor %}
        </table>

        
    </div>

{%endblock%}

appteams/templates/coachs.html
{% extends 'layouts/barra.html' %}
{% load static %}
{%block blockname%}
<h1 class="titulo">Lista de Coachs</h1>
<div class="botones">
    <a href='/registrar-coach' class="agregar">Agregar</a>
</div>
<div class="contenedor-tabla">
    <table class="tabla">
        <tr >
            <td class="encabezado">Nombre</td>
            <td class="encabezado">Foto</td>
            <td class="encabezado" colspan="2"></td>

        </tr>

        {%for coach in coachs%}
        <tr>
            <td>{{coach.name}}</td>
            <td><img src="{{ coach.photo.url }}" alt="Foto del coach" width="150"></td>
            <td><a href='/editar-coach/{{coach.id}}' class="editar">Editar</a></td>
            <td><a href="{% url 'appteams:eliminar-coach' coach.id %}" class="eliminarr">Eliminar</a></td> 
        </tr>
        {% endfor %}
    </table>
</div>

{%endblock%}

appteams/templates/equipos.html
{% extends 'layouts/barra.html' %}
{% load static %}
{%block blockname%}
    <h1 class="titulo">Lista de los equipos</h1>
    <div class="botones">
        <a href='/registrar-cedula' class="agregar">Agregar</a>
    </div>
    <div class="contenedor-tabla">
        
        <table class="tabla">
            <tr >
                <td class="encabezado">Nombre</td>
                <td class="encabezado">Foto</td>
                <td class="encabezado">Coach</td>
                <td class="encabezado">Liga</td>
                <td class="encabezado" colspan="2"></td>
            </tr>

            {%for equipo in equipos%}
            <tr>
                <td>{{equipo.name}}</td>
                {% if equipo.photo %}
                <td><img src="{{ equipo.photo.url }}" alt="Foto del equipo" width="150"></td>
                {% else %}
                    <td>No hay foto disponible</td>
                {% endif %}
                <td>{{equipo.coach_id.name}}</td>
                <td>{{equipo.liga_id.name}}</td>
                <td><a href='/editar-equipo/{{equipo.id}}' class="editar">Editar</a></td>
                <td><a href="{% url 'appteams:eliminar-equipo' equipo.id %}" class="eliminar">Eliminar</a></td>
            </tr>
            {% endfor %}
        </table>
    </div>

{%endblock%}

appteams/templates/estadios.html
{% extends 'layouts/barra.html' %}

{%block blockname%}
    <h1 class="titulo">Lista de los Estadios</h1>
    <div class="botones">
        <a href='/registrar-estadio' class="agregar">Agregar</a>
    </div>
    <div class="contenedor-tabla">
        <table class="tabla">
            <tr >
                <td class="encabezado">Liga</td>
                <td class="encabezado">Nombre</td>
                <td class="encabezado">Foto</td>
                <td class="encabezado" colspan="2"></td>
            </tr>

            {%for estadio in estadios%}
            <tr>
                <td>{{estadio.liga_id.name}}</td>
                <td>{{estadio.name}}</td>
                <td><img src="{{ estadio.photo.url }}" alt="Foto del estadio" width="150"></td>
                <td><a href='/editar-estadio/{{estadio.id}}' class="editar">Editar</a></td>
                <td><a href="{% url 'appteams:eliminar-estadio' estadio.id %}" class="eliminar">Eliminar</a></td>
                
            </tr>
            {% endfor %}
        </table>
    </div>

{%endblock%}

appteams/templates/formulario.html
{% extends 'layouts/barra.html' %}
{%block blockname%}
<form method="post" enctype="multipart/form-data" >
    {% csrf_token %}
    {% if error%}
        <h2>{{error}}</h2>
    {%else%}
        {{ form.as_p}}  {# Esto renderizará los campos del formulario como párrafos #}
        <button type="submit">Guardar</button>
    {% endif %}
</form>
{%endblock%}

appteams/templates/jugadores.html
{% extends 'layouts/barra.html' %}
{% load static %}
{%block blockname%}
<h1 class="titulo">Lista de Jugadores</h1>
<div class="botones">
    <a href='/registrar-jugador' class="agregar">Agregar</a>
</div>
<div class="contenedor-tabla">
    <table class="tabla">
        <tr >
            <td class="encabezado">Equipo</td>
            <td class="encabezado">Jugador</td>
            <td class="encabezado">Foto</td>
            <td class="encabezado">Numero</td>
            <td class="encabezado">Posicion</td>
            <td class="encabezado" colspan="2"></td>

        </tr>

        {%for jugador in jugadores%}
        <tr>
            <td>{{jugador.team.name}}</td> 
            <td>{{jugador.name}}</td>
            <td><img src="{{ jugador.photo.url }}" alt="Foto del jugador" width="150"></td>
            <td>{{jugador.numero}}</td>
            <td>{{jugador.posicion}}</td>
            <td><a href='/editar-jugador/{{jugador.id}}' class="editar">Editar</a></td>
            <td><a href="{% url 'appteams:eliminar-jugador' jugador.id %}" class="eliminar">Eliminar</a></td>
            

        </tr>
        {% endfor %}
    </table>
</div>

{%endblock%}

appteams/templates/ligas.html
{% extends 'layouts/barra.html' %}
{%block blockname%}
    <h1 class="titulo">Lista de ligas de fútbol</h1>
    <div class="botones">
        <a href='/registrar-League' class="agregar">Agregar</a>
    </div>
    <div class="contenedor-tabla">
        <table class="tabla">
            <tr >
                <td class="encabezado">Nombre</td>
                <td class="encabezado">Foto</td>
                <td class="encabezado" colspan="2"></td>
            </tr>

            {%for liga in ligas%}
            <tr>
                <td>{{liga.name}}</td>
                <td><img src="{{ liga.foto.url }}" alt="Foto de la liga" width="150"></td>
                <td><a href='/editar-liga/{{liga.id}}' class="editar">Editar</a></td>
                <td><a href="{% url 'appteams:eliminar-liga' liga.id %}" class="eliminar">Eliminar</a></td> 
            </tr>
            {% endfor %}
        </table>
    </div>

{%endblock%}

appteams/templates/plays.html
{% extends 'layouts/barra.html' %}
{%block blockname%}

    <h1 class="titulo">Lista de Juegos</h1>
    <div class="botones">
        <a href='/registrar-Play' class="agregar">Agregar</a>
    </div>
    <div class="contenedor-tabla">
        <table class="tabla">
            <tr >
                <td class="encabezado">Folio</td>
                <td class="encabezado">Fecha</td>
                <td class="encabezado">Liga</td>
                <td class="encabezado">Equipo Local</td>
                <td class="encabezado">Equipo Visitante</td>
                <td class="encabezado">Estadio</td>
                <td class="encabezado" colspan="4">Arbitros</td>
                <td class="encabezado" colspan="2"></td>
                
            </tr>

            {%for juego in juegos%}
            <tr>
                <td>{{juego.folio}}</td>
                <td>{{juego.fecha}}</td>
                <td>{{juego.liga}}</td>
                <td>{{juego.team1}}</td>
                <td>{{juego.team2}}</td>
                <td>{{juego.estadio}}</td>
                <td><p>{{juego.arbitro_1}}</p> <p class="posicion_arb">{{juego.posicion_arbitro_1}}</p></td>
                <td><p>{{juego.arbitro_2}}</p> <p class="posicion_arb">{{juego.posicion_arbitro_2}}</p></td>
                <td><p>{{juego.arbitro_3}}</p> <p class="posicion_arb">{{juego.posicion_arbitro_3}}</p></td>
                <td><p>{{juego.arbitro_4}}</p> <p class="posicion_arb">{{juego.posicion_arbitro_4}}</p></td>
                <td><a href='/editar-juego/{{juego.id}}' class="editar">Editar</a></td>
                <td><a href="{% url 'appteams:eliminar-juego' juego.id %}" class="eliminar">Eliminar</a></td>
            </tr>
            {% endfor %}
        </table>
    </div>

{%endblock%}